name: Install python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install:
    strategy:
     matrix:
      python-version: 
       - "3.9"
       - "3.10"
       - "3.11"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ strategy.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "${{ strategy.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
